### ISSUE TITLE
[BUG] Items not spawning in chests

### ISSUE THREAD

**Issue by RustBandit** [Erfurt92/MagicalJewelry#6] opened 2021-01-31 09:18 UTC
Hey, so I can't find these in chests around the world, turned up the rarity, made a new world in creative, and set all the dimension spawn settings to vanilla minecraft. I am using other mods, but other ites are spawning

**Comment by Erfurt92** [comment] 2021-01-31 11:51
Firstly turning up the rarity doesn't make the jewels spawn more frequently in chests, it just change the chance of it being a particular rarity, the spawn rate for chests is only 1% per chest.
Secondly, for me to check if everything is working correctly, I would need more information. The information that you should have seen when you created this issue.
![Bug issue template](https://user-images.githubusercontent.com/20155513/106382898-d5667900-63c2-11eb-974f-d42200677a64.png)

If you want to change the spawn rate, you would need to make your own datapack for it

**Comment by Erfurt92** [comment] 2021-01-31 22:24
As far as I can tell, everything is working as intended, and based on the information given, I think you might have misunderstood, what the config option for the rarity droprate did. So I'm going to close the issue, if you have any other information, post it here, and I'll take another look into the problem. But do keep in mind that if you want the jewels to appear more in chest, you'll have to make a datapack to overwrite the default 1% chance.

**Closed as completed by Erfurt92** 2021-01-31 22:24 UTC
Labels: bug
